language: python
python:
    - 2.7
env:
    - DEBUG=1
cache: pip
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    coverage run --source='.' ./manage.py test
after_success:
    coveralls
