version: '2'
services:
  web:
    build: .
    command: python manage.py dns_server
    environment:
        - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    ports:
      - "53:10053"
      - "53:10053/udp"